In [1]:
%load_ext autoreload
%autoreload 2

In [17]:
import sys
from pathlib import Path

for project_root in (Path.cwd(), *Path.cwd().parents):
    if (project_root / "src").exists():
        sys.path.insert(0, str(project_root))
        break

import pandas as pd

from src.data.loaders import load_yambda_lag, split_and_reindex

In [18]:
config = {
    "ml-20m": {
        "max_seq_len": 200,
        "test_quantile": 0.1,
        "gap_seconds": 0,
        "interactions_path": "/Users/hadhad/HSE/нейро реки/проект/Actions-Speak-Louder-than-Words-research/tmp/ml-20m.zip", # https://grouplens.org/datasets/movielens/20m/
        "col_mapping": {
            "userid": "user_id",
            "movieid": "item_id",
            "rating": "feedback",
            "timestamp": "timestamp",
        },
    },
    "yambda": {
        "max_seq_len": 200,
        "test_quantile": 0.1,
        "gap_seconds": 0,
        "interactions_path": None,
        "col_mapping": {
            "uid": "user_id",
            "item_id": "item_id",
            "timestamp": "timestamp",
        },
    },
    "yambda-retrieval": {
        "max_seq_len": 100,
        "test_quantile": 0.1,
        "gap_seconds": 0,
        "interactions_path": "/Users/hadhad/HSE/нейро реки/проект/Actions-Speak-Louder-than-Words-research/tmp/yambda-10m.parquet",
        "col_mapping": {
            "uid": "user_id",
            "item_id": "item_id",
            "timestamp": "timestamp",
        },
    },
    "amzn-books": {
        "max_seq_len": 50,
        "test_quantile": 0.1,
        "gap_seconds": 0,
        "interactions_path": "/Users/hadhad/HSE/нейро реки/проект/Actions-Speak-Louder-than-Words-research/tmp/ratings_Books.csv.gz", # https://mcauleylab.ucsd.edu/public_datasets/data/amazon_2023/benchmark/0core/rating_only/Books.csv.gz
        "col_mapping": {
            "user_id": "user_id",
            "parent_asin": "item_id",
            "rating": "feedback",
            "timestamp": "timestamp",
        },
    },
}

In [ ]:
yambda_df = load_yambda_lag(interactions_path=None, config=config["yambda"])

In [20]:
yambda_train, yambda_test, yambda_data_description = split_and_reindex(yambda_df, config=config["yambda"])

In [24]:
yambda_train

,user_id,timestamp,item_id,played_ratio_pct,track_length_seconds,is_like,is_full_play,is_skip,user_lag_listen_cnt,user_lag_like_cnt,...,ui_lag_skip_cnt,user_lag_avg_played_ratio,item_lag_avg_played_ratio,ui_lag_avg_played_ratio,artist_ids,artist_id,album_ids,album_id,feedback,action_code
0,0,6300205,318,100,170,False,True,False,568.0,5.0,...,0.0,83.464789,47.592885,0.0,[205876],205876,"[762872, 1947879]",762872,1,2
1,0,8508655,318,55,170,False,False,False,1109.0,7.0,...,0.0,81.301172,46.525994,100.0,[205876],205876,"[762872, 1947879]",762872,1,0
3,0,12127075,939,97,280,False,True,False,1302.0,7.0,...,0.0,78.709677,56.202749,0.0,[452447],452447,[2558848],2558848,1,2
5,0,7042790,1306,100,140,False,True,False,854.0,7.0,...,0.0,83.528103,66.121739,0.0,[700950],700950,[1105922],1105922,1,2
6,0,8016090,1306,100,140,False,True,False,1053.0,7.0,...,0.0,82.294397,65.766423,100.0,[700950],700950,[1105922],1105922,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22463550,8539,19676790,459997,100,200,False,True,False,156.0,3.0,...,0.0,88.358974,62.695924,100.0,[1176554],1176554,[2092838],2092838,1,2
22463551,8539,22063255,459997,100,200,False,True,False,308.0,3.0,...,0.0,91.746753,62.453086,100.0,[1176554],1176554,[2092838],2092838,1,2
22463552,8539,19416280,461249,100,205,False,True,False,94.0,3.0,...,0.0,92.914894,64.560065,0.0,[418058],418058,[1265248],1265248,1,2
22463553,8539,20248090,461249,100,205,False,True,False,164.0,3.0,...,0.0,88.926829,64.467666,100.0,[418058],418058,[1265248],1265248,1,2
22463554,8539,22066375,461249,100,205,False,True,False,324.0,3.0,...,0.0,92.154321,64.226022,100.0,[418058],418058,[1265248],1265248,1,2

In [25]:
datasets = {
    # "ml-20m": {
    #     "train": ml_train,
    #     "test": ml_test,
    #     "desc": ml_data_description,
    # },
    "yambda": {
        "train": yambda_train,
        "test": yambda_test,
        "desc": yambda_data_description,
    },
    # "amzn-books": {
    #     "train": amzn_train,
    #     "test": amzn_test,
    #     "desc": amzn_data_description,
    # },
}

In [26]:
for ds in datasets.values():
    display(ds['train'].head())

,user_id,timestamp,item_id,played_ratio_pct,track_length_seconds,is_like,is_full_play,is_skip,user_lag_listen_cnt,user_lag_like_cnt,...,ui_lag_skip_cnt,user_lag_avg_played_ratio,item_lag_avg_played_ratio,ui_lag_avg_played_ratio,artist_ids,artist_id,album_ids,album_id,feedback,action_code
0,0,6300205,318,100,170,False,True,False,568.0,5.0,...,0.0,83.464789,47.592885,0.0,[205876],205876,"[762872, 1947879]",762872,1,2
1,0,8508655,318,55,170,False,False,False,1109.0,7.0,...,0.0,81.301172,46.525994,100.0,[205876],205876,"[762872, 1947879]",762872,1,0
3,0,12127075,939,97,280,False,True,False,1302.0,7.0,...,0.0,78.709677,56.202749,0.0,[452447],452447,[2558848],2558848,1,2
5,0,7042790,1306,100,140,False,True,False,854.0,7.0,...,0.0,83.528103,66.121739,0.0,[700950],700950,[1105922],1105922,1,2
6,0,8016090,1306,100,140,False,True,False,1053.0,7.0,...,0.0,82.294397,65.766423,100.0,[700950],700950,[1105922],1105922,1,2

In [27]:
# статистики по датасетам

stats = []
for name, d in datasets.items():
    train, test, desc = d["train"], d["test"], d["desc"]
    n_train = len(train)
    n_test = len(test)
    n_total = n_train + n_test
    stats.append({
        "dataset": name,
        "n_train": n_train,
        "n_test": n_test,
        "n_total": n_total,
        "train_share": round(n_train / n_total, 3),
        "test_share": round(n_test  / n_total, 3),
        "n_train_users": train[desc["users"]].nunique(),
        "n_test_users": test[desc["users"]].nunique(),
        "n_items": train[desc["items"]].nunique(),
    })

pd.DataFrame(stats)

,dataset,n_train,n_test,n_total,train_share,test_share,n_train_users,n_test_users,n_items
0,yambda,20215747,2073034,22288781,0.907,0.093,8540,7407,461315

In [28]:
import importlib

import torch

import src.data.hstu_typed_dataset as hstu_typed_dataset_module
import src.HSTU.training.hstu.hstu_typed_pipeline as hstu_typed_pipeline_module

importlib.reload(hstu_typed_dataset_module)
importlib.reload(hstu_typed_pipeline_module)

from src.data.hstu_typed_dataset import (
    YAMBDA_HASH_CARDINALITY,
    YAMBDA_LABEL_COLUMNS,
    YAMBDA_MULTIVALENT_FEATURES_CONFIG,
    YAMBDA_SPARSE_FEATURES_CONFIG,
    add_yambda_multihash_feature_tokens,
    yambda_multihash_token_schema,
)
from src.HSTU.training.hstu.hstu_typed_pipeline import (
    TypedHSTUExperimentConfig,
    build_typed_hstu_dataloaders,
    build_typed_hstu_model,
    evaluate_typed_hstu,
    train_typed_hstu,
)

In [29]:
CARDINALITY = YAMBDA_HASH_CARDINALITY

EPOCHS = 3
LR = 1e-3
EMBEDDING_DIM = 32
NUM_HEADS = 4
HEAD_DIM = 16
DROPOUT = 0.1
MAX_HSTU_EVENTS = 64

yambda_train_typed, yambda_test_typed = add_yambda_multihash_feature_tokens(
    train=yambda_train,
    test=yambda_test,
)
yambda_schema = yambda_multihash_token_schema(
    train=yambda_train_typed,
    test=yambda_test_typed,
)

hash train artist_ids (first element): 100%|██████████| 20215747/20215747 [00:12<00:00, 1683581.55it/s]
hash test artist_ids (first element): 100%|██████████| 2073034/2073034 [00:01<00:00, 1377071.61it/s]
hash train album_ids (first element): 100%|██████████| 20215747/20215747 [00:15<00:00, 1287848.52it/s]
hash test album_ids (first element): 100%|██████████| 2073034/2073034 [00:01<00:00, 1387743.08it/s]

In [31]:
{
    "hash_cardinality": CARDINALITY,
    "sparse_hash_seeds": YAMBDA_SPARSE_FEATURES_CONFIG,
    "multivalent_hash_seeds": YAMBDA_MULTIVALENT_FEATURES_CONFIG,
    "label_columns": YAMBDA_LABEL_COLUMNS,
    "epochs": EPOCHS,
    "lr": LR,
    "embedding_dim": EMBEDDING_DIM,
    "num_heads": NUM_HEADS,
    "head_dim": HEAD_DIM,
    "dropout": DROPOUT,
    "max_history_events": MAX_HSTU_EVENTS,
    "tokens_per_event_upper_bound": yambda_schema.tokens_per_event,
    "max_token_seq_len_upper_bound": (MAX_HSTU_EVENTS + 1) * yambda_schema.tokens_per_event,
    "num_token_types": yambda_schema.num_token_types,
    "feature_vocab_sizes": yambda_schema.feature_vocab_sizes,
    "sample_artist_tokens": yambda_train_typed["artist_ids_token"].head().tolist(),
    "sample_album_tokens": yambda_train_typed["album_ids_token"].head().tolist(),
}

{'hash_cardinality': 65536,
 'sparse_hash_seeds': {'item_id': (11, 22), 'uid': (33, 44)},
 'multivalent_hash_seeds': {'artist_ids': (55, 66), 'album_ids': (77, 88)},
 'label_columns': ('is_like', 'is_full_play'),
 'epochs': 3,
 'lr': 0.001,
 'embedding_dim': 32,
 'num_heads': 4,
 'head_dim': 16,
 'dropout': 0.1,
 'max_history_events': 64,
 'tokens_per_event_upper_bound': 3,
 'max_token_seq_len_upper_bound': 195,
 'num_token_types': 4,
 'feature_vocab_sizes': {2: 65536, 3: 65536},
 'sample_artist_tokens': [28050, 28050, 28863, 8938, 8938],
 'sample_album_tokens': [32407, 32407, 64157, 55891, 55891]}

In [32]:
hstu_config = TypedHSTUExperimentConfig(
    max_events_len=MAX_HSTU_EVENTS,
    train_batch_size=256,
    eval_batch_size=256,
    num_epochs=EPOCHS,
    learning_rate=LR,
    weight_decay=0.0,
    output_size=2,
    label_columns=YAMBDA_LABEL_COLUMNS,
    embedding_dim=EMBEDDING_DIM,
    num_blocks=2,
    num_heads=NUM_HEADS,
    linear_dim=HEAD_DIM,
    attention_dim=HEAD_DIM,
    input_dropout_rate=DROPOUT,
    linear_dropout_rate=DROPOUT,
    attn_dropout_rate=DROPOUT,
    enable_relative_attention_bias=True,
    device="cuda" if torch.cuda.is_available() else "cpu",
)

(
    hstu_train_loader,
    hstu_eval_loader,
    hstu_train_dataset,
    hstu_eval_dataset,
    hstu_test_events,
) = build_typed_hstu_dataloaders(
    train=yambda_train_typed,
    test=yambda_test_typed,
    schema=yambda_schema,
    max_events_len=hstu_config.max_events_len,
    train_batch_size=hstu_config.train_batch_size,
    eval_batch_size=hstu_config.eval_batch_size,
    user_col=yambda_data_description["users"],
    item_col=yambda_data_description["items"],
    time_col=yambda_data_description["timestamp"],
    label_columns=hstu_config.label_columns,
    num_workers=hstu_config.num_workers,
)

{
    "train_samples": len(hstu_train_dataset),
    "eval_samples": len(hstu_eval_dataset),
    "target_users": len(hstu_test_events),
    "max_history_events": hstu_config.max_events_len,
    "max_token_seq_len": (hstu_config.max_events_len + 1) * yambda_schema.tokens_per_event,
    "train_batch_size": hstu_config.train_batch_size,
    "eval_batch_size": hstu_config.eval_batch_size,
}

build event histories: 100%|██████████| 8540/8540 [00:45<00:00, 189.28it/s]
build event histories: 100%|██████████| 7407/7407 [00:02<00:00, 2668.72it/s]
build typed train chunks: 100%|██████████| 8540/8540 [02:04<00:00, 68.49it/s]
collate train batches: 100%|██████████| 1251/1251 [00:18<00:00, 67.00it/s]
build typed eval chunks: 100%|██████████| 8540/8540 [00:10<00:00, 791.66it/s]
collate eval batches: 100%|██████████| 143/143 [00:01<00:00, 81.09it/s]

{'train_samples': 1251,
 'eval_samples': 143,
 'target_users': 7407,
 'max_history_events': 64,
 'max_token_seq_len': 195,
 'train_batch_size': 256,
 'eval_batch_size': 256}

In [33]:
hstu_model = build_typed_hstu_model(
    num_items=yambda_data_description["n_items"],
    schema=yambda_schema,
    experiment_config=hstu_config,
)

hstu_model.to(hstu_config.device)
hstu_optimizer = torch.optim.AdamW(
    hstu_model.parameters(),
    lr=hstu_config.learning_rate,
    weight_decay=hstu_config.weight_decay,
)

In [34]:
params_sum = 0
trainable_sum = 0

for name, module in hstu_model.encoder.named_children():
    params = sum(p.numel() for p in module.parameters())
    trainable = sum(p.numel() for p in module.parameters() if p.requires_grad)
    print(f"{name}: total={params:,}, trainable={trainable:,}")

    params_sum += params
    trainable_sum += trainable
print()
print(f"params_sum={params_sum:,}, trainable_sum={trainable_sum:,}")

token_embedding: total=18,956,544, trainable=18,956,544
pos_embeddings: total=6,240, trainable=6,240
event_pos_embeddings: total=2,080, trainable=2,080
input_dropout: total=0, trainable=0
blocks: total=21,964, trainable=21,964

params_sum=18,986,828, trainable_sum=18,986,828

In [35]:
losses, eval_history = train_typed_hstu(
    model=hstu_model,
    train_loader=hstu_train_loader,
    optimizer=hstu_optimizer,
    num_epochs=hstu_config.num_epochs,
    device=hstu_config.device,
    eval_loader=hstu_eval_loader,
    label_columns=hstu_config.label_columns,
)
losses, eval_history

typed epoch 1/3:   0%|          | 0/1251 [00:00<?, ?it/s]

Typed HSTU NE evaluation: 100%|██████████| 143/143 [00:21<00:00,  6.68it/s]

typed epoch 1/3: loss=0.2398, ne_c_task=0.4183, ne_e_task=0.9448

Typed HSTU NE evaluation: 100%|██████████| 143/143 [00:19<00:00,  7.30it/s]

typed epoch 2/3: loss=0.1713, ne_c_task=0.4045, ne_e_task=0.9306

Typed HSTU NE evaluation: 100%|██████████| 143/143 [00:18<00:00,  7.66it/s]

typed epoch 3/3: loss=0.1585, ne_c_task=0.3947, ne_e_task=0.9441

([0.2398121754783328, 0.17128462021284685, 0.15852473416861862],
 [{'ne_e_task': 0.9447884547506626, 'ne_c_task': 0.41832459516196946},
  {'ne_e_task': 0.9306389702648066, 'ne_c_task': 0.40450627613958284},
  {'ne_e_task': 0.9440815503271703, 'ne_c_task': 0.3947481709363843}])

In [36]:
eval_history_df = pd.DataFrame(eval_history)
eval_history_df.insert(0, "epoch", range(1, len(eval_history_df) + 1))
eval_history_df

   epoch  ne_e_task  ne_c_task
0      1   0.944788   0.418325
1      2   0.930639   0.404506
2      3   0.944082   0.394748

## Normalized Entropy

NE считается так же, как в `deeprecsys_project/examples/example.ipynb`: event-level logits supervised head сравниваются с `is_like` и `is_full_play`, затем считается normalized entropy для E-task и C-task.

In [37]:
hstu_metrics, hstu_eval_outputs = evaluate_typed_hstu(
    model=hstu_model,
    eval_loader=hstu_eval_loader,
    device=hstu_config.device,
    label_columns=hstu_config.label_columns,
)

hstu_metrics

Typed HSTU NE evaluation: 100%|██████████| 143/143 [00:19<00:00,  7.50it/s]

{'ne_e_task': 0.9440815503271703, 'ne_c_task': 0.3947481709363843}

In [38]:
pd.DataFrame(
    {
        "model": ["typed hstu"],
        "e_task": [hstu_metrics["ne_e_task"]],
        "c_task": [hstu_metrics["ne_c_task"]],
    }
)

        model    e_task    c_task
0  typed hstu  0.944082  0.394748